Repository todomateclone/BE, pull requests merged in 2022-12, with the labels that each got.

#3 Init Commit
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/team6/todomateclone/TodomatecloneApplication.java
  src/main/java/com/team6/todomateclone/common/TimeStamped.java
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
  src/main/java/com/team6/todomateclone/common/exception/CustomException.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtUtil.java
  src/main/java/com/team6/todomateclone/common/response/ResponseMessage.java
  src/main/java/com/team6/todomateclone/common/security/UserDetailsImpl.java
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/controller/MemberInfoController.java
  src/main/java/com/team6/todomateclone/member/dto/RequestLoginMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/RequestSignupMemberDto.java
  src/main/java/com/team6/todomateclone/member/entity/Member.java
  src/main/java/com/team6/todomateclone/member/repository/MemberRepository.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
  src/main/java/com/team6/todomateclone/tag/dto/RequestTagDto.java
  src/main/java/com/team6/todomateclone/tag/dto/ResponseTagDto.java
  src/main/java/com/team6/todomateclone/tag/entity/Tag.java
  src/main/java/com/team6/todomateclone/tag/mapper/TagMapper.java
  src/main/java/com/team6/todomateclone/tag/repository/TagRepository.java
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/dto/RequestTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/ResponseTodoDto.java
  src/main/java/com/team6/todomateclone/todo/entity/Todo.java
  src/main/java/com/team6/todomateclone/todo/mapper/TodoMapper.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRespository.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
  src/main/resources/application.properties
  src/test/java/com/team6/todomateclone/TodomatecloneApplicationTests.java
Labels: init

#4 feat : PR Template 추가
  .github/ISSUE_TEMPLATE/issue--✔feature-.md
  .github/ISSUE_TEMPLATE/issue--🐞bug.md
  .github/ISSUE_TEMPLATE/issue--💎refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#5 Feature/cicd
  .github/workflows/gradle.yml
  appspec.yml
  build.gradle
  build.gradle.kts
  scripts/start.sh
  scripts/stop.sh
Labels: init

#6 feat : httpshealthycheck
  src/main/java/com/team6/todomateclone/common/HealthyCheckController.java
Labels: enhancement

#8 Feature/cicd
  .github/workflows/gradle.yml
Labels: bug

#9 fix : PropertySource 오타 수정
  src/main/java/com/team6/todomateclone/TodomatecloneApplication.java
Labels: bug

#11 Test : todo등록 구현(시큐리티 사용자인증 필요)
  build.gradle
  src/main/java/com/team6/todomateclone/common/exception/ErrorResponse.java
  src/main/java/com/team6/todomateclone/common/response/SuccessResponse.java
  src/main/java/com/team6/todomateclone/member/entity/Member.java
  src/main/java/com/team6/todomateclone/tag/entity/Tag.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/dto/RequestTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/RequestTodoUpdateDto.java
  src/main/java/com/team6/todomateclone/todo/dto/createdto/CreateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/createdto/RequestCreateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/createdto/ResponseCreateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/entity/Todo.java
  src/main/java/com/team6/todomateclone/todo/mapper/TodoMapper.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
  src/main/resources/application.properties
Labels: test

#13 ✨feat : 회원 가입 시 회원 닉네임, 소개, 이미지저장
  build.gradle
  src/main/java/com/team6/todomateclone/common/config/AwsS3Config.java
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorCodeEnum.java
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/controller/MemberInfoController.java
  src/main/java/com/team6/todomateclone/member/dto/RequestSignupMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/RequestUpdateInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseUpdateImageMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseUpdateInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/entity/Member.java
  src/main/java/com/team6/todomateclone/member/mapper/MemberMapper.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
  src/main/resources/application.properties
Labels: enhancement, fix

#15 feat : Security 설정
  .gitignore
  build.gradle
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorCodeEnum.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtUtil.java
  src/main/java/com/team6/todomateclone/common/jwt/exception/JwtExceptionHandlerFilter.java
  src/main/java/com/team6/todomateclone/common/security/UserDetailsImpl.java
  src/main/java/com/team6/todomateclone/common/security/UserDetailsServiceImpl.java
  src/main/java/com/team6/todomateclone/member/repository/MemberRepository.java
Labels: enhancement

#16 fix : 예외 메시지 변수 수정
  src/main/java/com/team6/todomateclone/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtUtil.java
Labels: bug

#17 ♻️ Refactor : todo 예외 enum 수정 및 todo service 관련 내용 반영
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorCodeEnum.java
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
  src/main/resources/security.properties
Labels: refactor

#20 feat : 모든 URL 토큰 권한 허용
  src/main/java/com/team6/todomateclone/common/jwt/JwtAuthenticationFilter.java
Labels: bug, feat

#24 fix : HealthCheckController 수정
  src/main/java/com/team6/todomateclone/common/HealthyCheckController.java
Labels: bug

#23 feat : 로그인, 회원가입 기능 추가
  build.gradle
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorCodeEnum.java
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/dto/RequestLoginMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/RequestSignupMemberDto.java
  src/main/java/com/team6/todomateclone/member/entity/Member.java
  src/main/java/com/team6/todomateclone/member/mapper/MemberMapper.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
Labels: feat

#25 Feature/cicd
  src/main/java/com/team6/todomateclone/common/HealthyCheckController.java
Labels: bug

#28 refactor : 전반적인 시큐리티 코드 수정
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtUtil.java
  src/main/java/com/team6/todomateclone/common/jwt/exception/JwtExceptionHandlerFilter.java
  src/main/java/com/team6/todomateclone/common/security/UserDetailsServiceImpl.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
Labels: refactor

#26 ✨ Feat : Todo전체조회(월단위) 구현
  src/main/java/com/team6/todomateclone/common/response/ResponseMessage.java
  src/main/java/com/team6/todomateclone/common/response/SuccessMessage.java
  src/main/java/com/team6/todomateclone/tag/entity/Tag.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/dto/GetListDto/ResponseGetListTagsDto.java
  src/main/java/com/team6/todomateclone/todo/dto/GetListDto/ResponseGetListTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/GetListDto/ResponseGetListTodosDto.java
  src/main/java/com/team6/todomateclone/todo/dto/RequestTodoUpdateDto.java
  src/main/java/com/team6/todomateclone/todo/dto/ResponseTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/updatedto/RequestUpdateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/mapper/GetListTodoMapper.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRespository.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
Labels: feat

#27 refactor : Security 적용 후 컨트롤러 리팩토링
  src/main/java/com/team6/todomateclone/member/controller/MemberInfoController.java
  src/main/java/com/team6/todomateclone/member/entity/Member.java
Labels: refactor

#29 ♻️ Refactor : Security 적용
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorCodeEnum.java
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
  src/main/java/com/team6/todomateclone/tag/dto/ResponseTagDto.java
  src/main/java/com/team6/todomateclone/tag/entity/Tag.java
  src/main/java/com/team6/todomateclone/tag/mapper/TagMapper.java
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
Labels: refactor

#31 Feature/회원 가입 시 tag 생성
  src/main/java/com/team6/todomateclone/member/dto/ResponseInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseUpdateImageMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseUpdateInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/mapper/MemberMapper.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
  src/main/java/com/team6/todomateclone/tag/mapper/TagMapper.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: feat

#30 ✨ Feat : 태그 조회 기능 구현
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
Labels: feat

#34 ♻️ Refactor : 태그 삭제 조건 추가
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorCodeEnum.java
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
Labels: refactor

#35 ✨ Feat : Swagger 추가
  build.gradle
  src/main/java/com/team6/todomateclone/common/config/SwaggerConfig.java
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/controller/MemberInfoController.java
  src/main/java/com/team6/todomateclone/member/dto/RequestLoginMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/RequestSignupMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/RequestUpdateInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseInfoMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseUpdateImageMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/ResponseUpdateInfoMemberDto.java
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
  src/main/java/com/team6/todomateclone/tag/dto/RequestTagDto.java
  src/main/java/com/team6/todomateclone/tag/dto/ResponseTagDto.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/dto/GetListDto/ResponseGetListTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/createdto/RequestCreateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/createdto/ResponseCreateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/updatedto/RequestUpdateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/updatedto/ResponseUpdateTodoDto.java
  src/main/resources/application.properties
Labels: feat

#36 ♻️ Refactor : 로그인, 회원가입의 Dto를 RequestAuthDto로 수정
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/dto/RequestAuthMemberDto.java
  src/main/java/com/team6/todomateclone/member/dto/RequestLoginMemberDto.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
Labels: refactor

#37 🐛 Fix : HTTPS 요청 에러 해결
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorResponse.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtAuthenticationFilter.java
Labels: fix

#38 🐛 Fix : 회원페이지 Swagger 설정 복원(#35)
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
Labels: fix

#39 ♻️ Refactor : 전체코드 리팩토링
  src/main/java/com/team6/todomateclone/common/HealthyCheckController.java
  src/main/java/com/team6/todomateclone/common/TimeStamped.java
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtUtil.java
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/controller/MemberInfoController.java
  src/main/java/com/team6/todomateclone/member/entity/Member.java
  src/main/java/com/team6/todomateclone/member/service/MemberService.java
  src/main/java/com/team6/todomateclone/tag/dto/RequestTagDto.java
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/dto/GetListDto/ResponseGetListTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/updatedto/RequestUpdateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/updatedto/UpdateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/mapper/CreateTodoMapper.java
  src/main/java/com/team6/todomateclone/todo/mapper/UpdateTodoMapper.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRepository.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
  src/main/resources/application.properties
Labels: refactor

#42 ♻️ Refactor 스웨거 URI 시큐리티 허용
  src/main/java/com/team6/todomateclone/common/HealthyCheckController.java
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
  src/main/java/com/team6/todomateclone/common/jwt/JwtUtil.java
  src/main/java/com/team6/todomateclone/member/controller/MemberInfoController.java
  src/main/java/com/team6/todomateclone/tag/controller/TagController.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
Labels: refactor

#41 ♻️ Refactor : 태그 삭제 수정
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRepository.java
Labels: refactor

#43 ♻️ Refactor : validated exception 추가
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorExceptionHandler.java
  src/main/java/com/team6/todomateclone/common/exception/CustomErrorResponse.java
  src/main/java/com/team6/todomateclone/common/exception/ValidationGroups.java
  src/main/java/com/team6/todomateclone/common/exception/ValidationSequence.java
  src/main/java/com/team6/todomateclone/member/controller/MemberAuthController.java
  src/main/java/com/team6/todomateclone/member/dto/RequestAuthMemberDto.java
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/dto/createdto/RequestCreateTodoDto.java
  src/main/java/com/team6/todomateclone/todo/dto/updatedto/RequestUpdateTodoDto.java
Labels: refactor

#44 🐛 Fix: 태그 삭제 오류 수정
  src/main/java/com/team6/todomateclone/tag/service/TagService.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRepository.java
Labels: fix

#46 ✨ Feat: Todo 달성 기능 구현(Toggle방식) 및 API URL수정
  src/main/java/com/team6/todomateclone/todo/controller/TodoController.java
  src/main/java/com/team6/todomateclone/todo/entity/Todo.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRepository.java
  src/main/java/com/team6/todomateclone/todo/service/TodoService.java
Labels: feat

#47 ♻️ Refactor : 태그 등록 Request 수정
  src/main/java/com/team6/todomateclone/tag/mapper/TagMapper.java
  src/main/java/com/team6/todomateclone/todo/repository/TodoRepository.java
Labels: refactor

#49 ✨feature/S3 링크 CORS 추가
  src/main/java/com/team6/todomateclone/common/config/WebSecurityConfig.java
Labels: fix, feat

#51 📝 Docs readme 수정
  README.md
  img_2.png
  img_3.png
Labels: documentation
